-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtZ64l/YoufaKyEwq
i3oo9jHgFQhUGnWSvwV8smMcVwmgCgYIKoZIzj0DAQehRANCAATYl8rjSKy8VQ6m
7qGqukjSk7YD6J9RIvYKM0bUftHIqYaCDWXxcCkEKWUmd5FqDLIk/zYDHdN+9Ugx
dKcpQcsL
-----END PRIVATE KEY-----