import React, { useState, useEffect, useRef } from 'react';

function PortalTermsService(props) {
  return (
    <article className="portal-terms-container">
      <header>
        <span className="heading">Terms of Service</span>
      </header>

      <div className="content">
        <div className="terms-of-service-container">
          <p><b>BEFORE YOU USE THE TOPPINGS MARKETPLACE, CAVIAR MARKETPLACE, AND/OR TOPPINGS PORTAL ("PLATFORM") PLEASE READ THESE TERMS CAREFULLY. BY EXECUTING THE SIGN-UP SHEET WITH TOPPINGS OR USING THE PLATFORM, YOU, ANY ENTITIES THAT YOU REPRESENT AND ALL OF YOUR PARTICIPATING STORE LOCATIONS ("YOU" OR "MERCHANT") AGREE TO BE BOUND BY THESE TERMS IN ADDITION TO THE TERMS ON YOUR SIGN-UP SHEET.
SECTION 19 OF THIS AGREEMENT CONTAINS PROVISIONS THAT GOVERN HOW CLAIMS THAT YOU AND WE HAVE AGAINST EACH OTHER ARE RESOLVED, INCLUDING, WITHOUT LIMITATION, ANY CLAIMS THAT AROSE OR WERE ASSERTED BEFORE THE EFFECTIVE DATE OF THIS AGREEMENT. IN PARTICULAR, SECTION 19 SETS FORTH OUR ARBITRATION AGREEMENT WHICH WILL, WITH LIMITED EXCEPTIONS, REQUIRE DISPUTES BETWEEN US TO BE SUBMITTED TO BINDING AND FINAL ARBITRATION. UNLESS YOU OPT OUT OF THE ARBITRATION AGREEMENT: (1) YOU WILL ONLY BE PERMITTED TO PURSUE CLAIMS AND SEEK RELIEF AGAINST US ON AN INDIVIDUAL BASIS, NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS OR REPRESENTATIVE ACTION OR PROCEEDING; AND (2) YOU ARE WAIVING YOUR RIGHT TO SEEK RELIEF IN A COURT OF LAW AND TO HAVE A JURY TRIAL ON YOUR CLAIMS. THE ARBITRATION AGREEMENT COULD AFFECT YOUR RIGHT TO PARTICIPATE IN PENDING PROPOSED CLASS ACTION LITIGATION. PLEASE SEE SECTION 19 FOR MORE INFORMATION REGARDING THIS ARBITRATION AGREEMENT, THE POSSIBLE EFFECTS OF THIS ARBITRATION AGREEMENT, AND HOW TO OPT OUT OF THE ARBITRATION AGREEMENT.
</b></p>
          <ol>
            <li><b>Definitions.</b>
              <ol type="a">
                <li>“Topper” means independent third-party delivery contractor.</li>
                <li>“Delivery API” means the Toppings application programming interface (API) that allows the Merchant to exchange information with Toppings.</li>
                <li>“Toppings Data” shall mean any information that Toppings provides or makes accessible to Merchant through the Toppings Platform, including without limitation Personal Information.</li>
                <li>“Customer” means the customer who places an order for Merchant Products through the Toppings Platform or Toppings Portal.</li>
                <li>“Toppings Marketplace” means Toppings’ proprietary online communication platform where Customers can view and search for the menus of Merchants and/or place an order for Merchant Products via the Toppings website or mobile application for delivery by a Topper to the Customer or for pickup by Customer.</li>
                <li>“Toppings Platform” means Toppings Marketplace or Toppings App.</li>
                <li>“Toppings Portal” means the platform that enables delivery fulfillment for orders placed directly with the Merchant by the Customer.</li>
                <li>“Toppings Services” means Toppings Platform and, Toppings Portal, as applicable.</li>
                <li>“Portal Orders” means orders placed by Merchant for delivery fulfilment by Toppings.</li>
                <li>“Portal Term” means the term of the agreement between Toppings and Merchant for Toppings Portal.</li>
                <li>“Marketplace Orders” means orders for Merchant Products through the Toppings Platform from Customers for delivery by Toppers.</li>
                <li>“Merchant” means the restaurant or other entity that has agreed to participate in the Toppings Services.</li>
                <li>"Merchant Portal" is an online website, accessible at https:toppingsapp.com through which Merchant may and regularly should review and confirm its transactions, fees and charges and account on the Platform.</li>
                <li>“Merchant Products” includes all products offered for take-out or delivery orders at Merchant Stores.</li>
                <li>“Merchant Stores” means the Merchant restaurant locations that participate in the Toppings Services and includes: (i) Merchant Stores owned and operated by Merchant or its affiliates, and/or (ii) Merchant Stores owned and operated by Franchisees of Merchant or its affiliates.</li>
                <li>“Marketplace Term” means the term of the agreement between Toppings and Merchant for the Toppings Platform.</li>
                <li>“Order” means a Marketplace Order or a Portal Order, as applicable.</li>
                <li>“Order Equipment” means and includes any equipment reasonably required by Toppings for Merchant to receive and process Orders, including, without limitation, a tablet, fax machine, or other automated, electronic means of receiving Orders.</li>
                <li>“Personal Information” shall mean any information exchanged under this Agreement that (i) identifies or can be used to identify an individual (including without limitation, names, telephone numbers, addresses, signatures, email addresses or other unique identifiers); or (ii) that can reasonably be used to authenticate an individual (including without limitation, name, contact information, precise location information, access credentials, persistent identifiers and any information that may be considered ‘personal data’ or ‘personal information’ under applicable law).</li>
                <li>“Commission Rate” means the commission fees collected by Toppings in exchange for promoting and featuring the Merchant and Merchant Store(s) on the Toppings Platform, which is charged as a percentage of revenues transacted on the Toppings Platform.</li>
                <li>“Schedule for Later Order” shall mean an Order to be fulfilled at a particular time later in the same day or at a later date.</li>
                <li>“Terms” means the provisions herein.</li>
                <li>“Third Party Platform” means a technology interface, such as a middleware technology platform, other than the online order form and the Delivery API that enables Merchant to request delivery fulfillment and provide information necessary to enable such delivery fulfillment.</li>
              </ol>
            </li>
            <li><b>The Parties' Relationship.</b> Toppings provides an online marketplace platform using web-based technology that connects Merchants, independent delivery contractors ("Toppers") and Customers ("Platform"), as described in these Terms for Toppings Platform and Toppings Portal. Toppings is not a merchant, seller of goods, or delivery service; it is an online connection platform. Merchant and Toppings agree they are independent businesses whose relationship is governed by the Sign-Up Sheet and these Terms. Nothing in the Parties' agreements, relationship or transactions shall create or be construed as creating an agency, partnership, fiduciary or joint venture relationship between Toppings and Merchant (or Merchant's employees, representatives or locations), Toppings and Topper, or Toppings and Customers. Except as expressly set forth in the Sign-Up Sheet and these Terms, each Party shall be responsible for its own expenses, profits and losses.</li>
            <li><b>Toppings Platform Core Responsibilities.</b> . For Merchants that have agreed to participate in the Toppings Platform, Toppings and Merchant shall have the following responsibilities during the Marketplace Term:
              <ol type="a">
                <li>Toppings Core Responsibilities. Toppings will, in a timely manner:
                  <ol type="i">
                    <li>Display Merchant’s logo; a listing of the Merchant Stores; and a menu of Merchant Products on the Toppings Platform;</li>
                    <li>Accept Marketplace Orders from Customers;</li>
                    <li>Forward each Marketplace Order to the relevant Merchant Store; and</li>
                    <li>Forward each Marketplace Order to a Topper, so that the Topper can pick up the applicable Merchant Product(s) from the Merchant Store to deliver to the Customer.</li>
                    <li>Pay the Merchant in accord with the Parties' agreements, deduct the applicable Commission Rate, marketing fees (for identifiable orders), subscription fees,  Activation Fees, and any other fees (in each case, as may be adjusted by Toppings as required by any applicable statute, regulation, executive order, or other legal requirement that is either temporary or permanent in nature).</li>
                  </ol>
                </li>
                <li>Merchant Core Responsibilities. Merchant will, in a timely manner:
                <ol type="i">
                    <li>Provide Toppings with the Merchant’s in-store or take-out menu, including the price of each item on such menu;</li>
                    <li>Monitor Merchant’s menu and store information on the Toppings Platform, promptly make updates via the Merchant Portal to reflect the most up-to-date products, pricing and other information or immediately notify Toppings of any errors or changes in writing;</li>
                    <li>Accept all Marketplace Orders placed by Toppings from Merchant’s then-current menu;</li>
                    <li>Confirm all Marketplace Orders from Toppings;</li>
                    <li>Prepare the Merchant Products for each Marketplace Order for pickup by a Topper at the designated time;</li>
                    <li>Process Marketplace Orders in the order in which they are received;</li>
                    <li>Notify Toppings of any changes to the pricing, availability, description, or other characteristics of the Merchant Products;</li>
                    <li>Notify Toppings of its days and hours of operation, and remain open for business on Toppings the same days and hours of operation as Merchant’s in-store business; notify Toppings of any changes to Merchant’s hours of operations on holidays; and notify Toppings if Merchant closes earlier than Merchant’s standard hours of operation or plans to close earlier than Merchant’s standard hours of operation;</li>
                    <li>Notify all Merchant store staff members of the relationship with Toppings immediately upon execution of this Agreement;</li>
                    <li>Provide the same utensils, napkins, bags and other materials that Merchant would typically provide in a standard take-out or delivery order, subject to Section 15(3)(i);</li>
                    <li>On an ongoing basis, review and confirm the transactions, fees and charges on orders via the Merchant Portal, and promptly communicate to Toppings any inaccuracies; and</li>
                    <li>If Toppings collects and passes tips from Customers to Merchant, Merchant will distribute such tips in accordance with applicable law, including but not limited to tip pooling laws.</li>
                  </ol>
                </li>
              </ol>
            </li>
            <li><b>Toppings Portal Core Responsibilities.</b> For Merchants that have agreed to participate in Toppings Portal, Toppings and Merchant shall have the following responsibilities during the Portal Term:
              <ol type="a">
                <li>Toppings Core Responsibilities. Toppings will, in a timely manner:
                  <ol type="i">
                    <li>Provide Merchant with an online order form or access to the Delivery API to submit requests for deliveries, or receive information through a Third Party Platform;</li>
                    <li>Forward requests to a Topper, so that the Topper can pick up the applicable Merchant Product(s) from the Merchant Store to deliver to the Customer.</li>
                  </ol>
                </li>
                <li>Merchant Core Responsibilities. Merchant will:
                  <ol type="i">
                    <li>Via the online order form, the Delivery API, or a Third Party Platform, provide information requested by Toppings including the Customer’s address, contact information, and any special instructions required for delivery; </li>
                    <li>Accept and collect payments from Customers for their respective orders;</li>
                    <li>Notify Customers prior to placing a Portal Order that their telephone numbers and other personal contact information will be shared with Toppings to enable deliveries to be made by Toppers and, in connection with the applicable deliveries, request the Customer’s consent to receive delivery status updates by e-mail, text messages, and telephone calls from Toppings and Toppers;</li>
                    <li>Notify Toppings if a Customer has not consented to receive delivery updates or has placed any restrictions on types of delivery updates such Customer consents to receive (e.g., no texts). Merchant hereby consents to receiving text messages and email confirmations from Toppings providing status updates and delivery confirmations in connection with each delivery.</li>
                    <li>On an ongoing basis, review and confirm the transactions, fees and charges on invoices and via the Merchant Portal, and promptly communicate to Toppings any inaccuracies.</li>
                  </ol>
                </li>
                <li>Portal Operating Procedures.
                  <ol type="i">
                    <li>Order Placement. Merchant agrees to submit a Portal Order for delivery fulfillment at least twenty-four (24) hours in advance of scheduled delivery, and in no event less than two (2) hours in advance of scheduled pick-up. Exceptions will be mutually agreed to by the Parties.</li>
                    <li>Hours of Operation. The pickup and dropoff of deliveries will be scheduled to take place during Toppings’s standard hours of availability, as may be updated from time to time in Toppings’s sole discretion. Merchant agrees to abide by the following standard procedures: (i) to notify Toppings of any changes to its hours of operations on federal holidays with reasonable advance notice; and (ii) to notify Toppings with reasonable advance notice if a Merchant location closes earlier than standard hours of operation or plans to close earlier than standard hours of operation.</li>
                    <li>Delivery Radii. Toppings will only accept Portal Orders to be delivered within a certain preset delivery radius based on either the Merchant or the End-Customer location, which will be communicated to Merchant.</li>
                    <li>Cancellations. Fees owed for any Portal Orders cancelled within twenty-four (24) hours of a Schedule for Later delivery are non-refundable. If provided more than two (2) hours notice, but less than twenty-four (24) hours notice, Toppings will make reasonable efforts to accommodate changes. </li>
                    <li>Notification. Merchant agrees to notify all staff members in Merchant Stores of Merchant’s relationship with Toppings prior to submitting any delivery requests to Toppings.</li>
                  </ol>
                </li>
              </ol>
            </li>
            <li><b>Refunds and Re-Orders.</b> Refunds and re-orders will be addressed as follows:
              <ol type="a">
                <li>Marketplace Order Refunds. In the event that Toppings, in its sole reasonable discretion, has to issue a refund, credit or re-order on an Customer’s Order, Merchant will prepare the food to the same specifications as the original Order (in the case of a re-order) and bear the full cost of that refund, credit or re-order, as applicable, unless the refund, credit or re-order is due to the fault of the Topper or Toppings.</li>
                <li>Portal Order Refunds. Merchant acknowledges and agrees that Toppings shall be responsible only for facilitating the delivery of Merchant Product(s) to Customers. Merchant shall be solely responsible for any customer complaints regarding Merchant Product(s), including without limitation, complaints regarding the nature, quality, content, number, or packaging of Merchant Product(s). Merchant agrees not to refer any Customer complaints directly to Toppings. Any complaints regarding the timeliness or quality of a Topper’s delivery service shall be reported by Merchant to Toppings. If the completion of a Portal Order is more than 45 minutes late and due to fault of Toppings, Toppings will reimburse Merchant for all or a portion of the delivery cost of the applicable Portal Order. If Merchant elects to refund a Customer for any reason, such election shall not obligate Toppings to provide a corresponding reimbursement to Merchant. In the event that a Merchant Product has been visibly damaged with proof from Customer, Toppings may reimburse Merchant for all or a portion of the order subtotal. For the purposes of this agreement, “Merchant Product” is the actual food or beverage item, not the packaging that contains the Merchant Product. In no event shall Toppings be obligated to issue any refunds directly to Customers.</li>
              </ol>
            </li>
            <li><b>Order Equipment. </b>With respect to the Toppings Platform, Merchant will install any equipment reasonably required by Toppings for Merchant to receive and process Orders (including, without limitation, a tablet, fax machine, or other automated, electronic means of receiving Orders) (“Order Equipment”). If any Order Equipment is provided by Toppings, Merchant will pay Toppings an Order Equipment Fee, as set forth in the Sign-Up Sheet, in exchange for the right to use the Order Equipment to access the Toppings Platform in order to receive, process, and accept Marketplace Orders. Any Order Equipment provided by Toppings will remain Toppings’s sole property and may be used solely for purposes related to fulfilling Merchant’s responsibilities under this Agreement. Merchant will inspect all hardware, and shall notify Toppings in writing if any Order Equipment is missing or was damaged as soon as practicable after discovering such damage. Toppings may restrict or rescind Merchant’s right to use the Toppings Platform at any time. Merchant will be responsible for any damage to or loss of any Order Equipment provided by Toppings (excluding ordinary wear and tear), which will be promptly reimbursed by Merchant (at the replacement cost thereof). Toppings may recover the replacement cost of damaged or lost Order Equipment by deducting such amount from weekly payments. Merchant agrees to pay all subscription fees and deposits reasonably charged by Toppings for Order Equipment, and agrees Toppings may deduct such fees and deposits from amounts payable by Toppings to Merchant.</li>
            <li><b>Payment, Fees, Title and Taxes. </b>Payment, fees, and taxes shall be addressed as follows:
              <ol type="a">
                <li>Toppings Platform. Toppings will pay for Marketplace Orders fulfilled by Merchant each week on a consistent day of the week, subject to change with no less than 10 days’ notice to Merchants by email or service notification. Toppings shall be entitled to deduct from such payments Toppings’s Commission Rate, marketing fees (for identifiable orders), Activation Fees, subscription fees, and any other fees which Toppings may notify you regarding with at least 7 days advance written notice. Merchant shall be responsible for all taxes, duties, and other governmental charges on the sale of Merchant Products and for remitting such taxes, duties, and other governmental charges to the appropriate authorities. In the event that Merchant raises the price for a menu item, Toppings shall not be required to remit the higher price to the Merchant until 3 business days after the Merchant first provides notice to  Toppings of such pricing change.</li>
                <li>Toppings Portal. Merchant will pay Toppings a fee per Portal Order as mutually agreed. Merchant shall be responsible for all taxes, duties, and other governmental charges on the sale of Merchant Products and for remitting such taxes, duties, and other governmental charges to the appropriate authorities. As agreed by the parties, payment of all fees under this Section 8(b) shall be as follows: (i) Merchant shall pay the fees by credit card or ACH at the time of ordering, or (ii) Toppings shall invoice Merchant on a monthly basis and Merchant shall pay the invoice within seven (7) days of receipt of such invoice. If any fee is not paid in full by the due date, Toppings may assess interest on the unpaid amount for the period beginning on the Payment Date and ending on the date that the amount is paid in full. The amount of interest to be paid shall not exceed the maximum rate under applicable law.</li>
                <li>To the extent that a third party provider provides services to Merchant via the Platform (for example, a middleware provider) and charges fees to Toppings, Toppings may pass through such third party’s fees to Merchant.</li>
                <li>In some jurisdictions in the United States, Toppings may be required to collect sales, use, or similar taxes from the Customer and remit such taxes directly to the tax authority. In such jurisdictions, Toppings will inform Merchant that Toppings will remit Collected Taxes to the tax authority and Toppings will be relieved of any responsibility to remit such Collected Taxes to Merchant.</li>
                <li>Merchant agrees, on an ongoing basis, to review and confirm its transactions, fees and charges on orders and invoices and via the Merchant Portal, and to promptly communicate to Toppings in writing any claimed inaccuracies, so that Toppings has the prompt opportunity to address and resolve any issues and so such issues do not persist, which Toppings and Merchant agree is in the best interests of both parties and their commercial relationship. Merchant agrees to communicate to Toppings any disagreement, non-conformity or any issue with any transaction, fee, charge or order within 60 days of the transaction, fee or order. Merchant shall be deemed to have acquiesced in and ratified, and to have waived any claim or objection regarding, each transaction, fee, charge and order if Merchant does not communicate a written claim or objection to Toppings regarding such transaction, fee, charge or order within such 60-day period.</li>
                <li>Merchant agrees that Merchant holds title to the goods or products that Merchant provides through the Platform until the goods are picked up from Merchant, and that title passes from the Merchant to the Customer upon pickup at the Merchant’s location. Merchant agrees that neither the Topper nor Toppings holds title to or acquires any ownership interest in any goods or products that Merchant prepares or provides through the Platform.</li>
              </ol>
            </li>
            <li><b>Payment Processing.</b> Payment processing services for Merchants on the Toppings Platform are provided by Stripe and are subject to the Stripe Connected Account Agreement, which includes the Stripe Services Agreement. By agreeing to these Terms, Merchant agrees to be bound by the Stripe Connected Account Agreement and the Stripe Services Agreement, as the same may be modified by Stripe from time to time. As a condition of Toppings enabling payment processing services through Stripe, Merchant agrees to provide Toppings accurate and complete information about Merchant’s representative and its business, and Merchant authorizes Toppings to share it and transaction information related to Merchant’s use of the payment processing services provided by Stripe. Stripe has been audited by a PCI-certified auditor and is certified to PCI Service Provider Level 1.</li>
            <li><b>Merchant Content and Trademark; Photographs of Menu Items.</b>
              <ol type="a">
                <li>During the Marketplace Term Merchant grants to Toppings a royalty-free, non-exclusive, limited, revocable, non-transferable, non-sublicensable right and license to use and display the Merchant Content in the provision of services to Merchant, including listing Merchant as a merchant on the Toppings Platform, referencing Merchant as a Toppings partner, and to promote Toppings’s products and services. As used herein, “Merchant Content” includes, without limitation, menus, photographs (either provided by Merchant or on Merchant’s website), trademarks, logos and other materials provided by Merchant to Toppings.</li>
                <li>If photographs of Merchant’s menu items are not available or if they do not meet Toppings’s requirements, as reasonably determined by Toppings, then Merchant consents to Toppings (i) engaging a professional photographer to take photographs of Merchant’s menu items (ii) enhancing the quality of Merchant’s existing photographs or (iii) using stock photos of the menu item, and displaying such photographs on the Toppings Platform as representations of Merchant’s menu items; provided that Merchant may contact Toppings support to have such photographs removed from the Merchant’s store listing and, in such event, Toppings will comply in a timely manner.</li>
              </ol>
            </li>
            <li><b>Confidential Information.</b>
              <ol type="a">
                <li>The term “Confidential Information” shall mean any confidential or proprietary business, technical or financial information or materials of a party (“Disclosing Party”) provided to the other party (“Receiving Party”) in connection with this Agreement, whether orally or in physical form, and shall include the terms of this Agreement. Without limiting the foregoing, Toppings Data is the Confidential Information of Toppings.</li>
                <li>Confidential Information does not include information that: (i) was rightfully known to the Receiving Party without restriction on use or disclosure prior to such information's being disclosed to the Receiving Party in connection with this Agreement; (ii) was or becomes public domain other than by the fault of the Receiving Party; (iii) was or is received by the Receiving Party on a non-confidential basis from a third party that, to the Receiving Party's knowledge, was not at the time under any obligation to maintain its confidentiality; or (iv) the Receiving Party can demonstrate by documentary records was independently developed by the Receiving Party without access to, use of or reference to any Confidential Information.</li>
                <li>The Receiving Party shall: (i) not access or use Confidential Information other than as necessary to exercise its rights or perform its obligations in accordance with this Agreement; (ii) except subject to its compliance with Section 11(d), not disclose or permit access to Confidential Information other than to its or any of its employees, officers, directors, consultants, agents, independent contractors, service providers, subcontractors and legal advisors (“Representatives”) who need to know such Confidential Information for purposes of the Receiving Party's exercise of its rights or performance of its obligations under and in accordance with this Agreement, and prior to any such disclosure are bound by written confidentiality and restricted use obligations at least as protective of the Confidential Information as the terms set forth in this Section; and (iii) safeguard the Confidential Information from unauthorized use, access or disclosure using at least the degree of care it uses to protect its most/similarly sensitive information and in no event less than a reasonable degree of care.</li>
                <li>If the Receiving Party is compelled by applicable Law to disclose any Confidential Information then, to the extent permitted by applicable Law, the Receiving Party shall promptly notify the Disclosing Party in writing of such requirement so that the Disclosing Party can seek a protective order or other remedy or waive its rights under Section 11(c) and provide reasonable assistance to the Disclosing Party, at the Disclosing Party's sole expense, in opposing or seeking protective limitations on disclosure.</li>
              </ol>
            </li>
            <li><b>Data Privacy and Security.</b>
              <ol type="a">
                <li>General. Merchant agrees not to access, collect, store, retain, transfer, use, disclose, or otherwise process in any manner Toppings Data, including without limitation Personal Information, except as required to perform under this Agreement. Merchant shall keep Toppings Data secure from unauthorized access and maintain the accuracy and integrity of Toppings Data in Merchant’s custody or control by using appropriate organizational, physical and technical safeguards. If Merchant becomes aware of any unauthorized access to Toppings Data, Merchant will immediately notify Toppings, consult and cooperate with investigations and potentially required notices, and provide any information reasonably requested by Toppings. Merchant agrees to implement and use security procedures, protocols or access credentials as reasonably requested by Toppings and will be responsible for damages resulting from Merchant’s failure to comply. Merchant will not allow any third party to use the Toppings Platform and will be responsible for damages resulting from sharing Merchant’s login credentials with unauthorized third parties or otherwise permitting unauthorized access to Merchant’s account. Merchants may not allow any third party to copy, modify, rent, lease, sell, distribute, reverse engineer, or otherwise attempt to gain access to the source code of the Toppings Platform; damage, destroy or impede the services provided through the Toppings Platform; transmit injurious code; or bypass or breach any security protection on the Toppings Platform.</li>
                <li>Delivery API. During the Term, Toppings grants to Merchant a non-exclusive, royalty-free, non-assignable, non-transferable, non-sublicensable, revocable, limited, fully paid-up license to access the Delivery API solely to transmit information to facilitate the Toppings Portal services. Merchant will not and will not permit or authorize any third party to (i) sell, license, rent, resell, lease, assign (except as permitted herein), transfer, or otherwise commercially exploit the Delivery API; (ii) circumvent or disable any security or other technological features or measures of, or otherwise gain or attempt to gain unauthorized access to the Delivery API; (iii) reverse engineer, dissemble, decompile, or otherwise attempt to derive the source code or the underlying ideas, algorithms, structure, or organization of the Delivery API; (iv) use the Delivery API in any manner or for any purpose that violates any law or regulation; and (v) use the Delivery API for a reason other than as specifically provided or intended under this Agreement. Each Party agrees not to perform any action with the intent of introducing to the other Party’s systems, products, or services (including the Delivery API) any viruses, worms, defect, Trojan horses, malware, or any items of a destructive nature.</li>
              </ol>
            </li>
            <li><b>Termination.</b> Merchant may terminate this Agreement for any reason at any time upon seven (7) days prior written notice. Toppings may terminate this Agreement or any promotion under this Agreement for any reason at any time upon written notice. Email shall suffice for written notice. Neither Merchant nor Toppings will be required to pay any fee in connection with a termination by either party, or be liable to the other as a result of termination of this Agreement for any damages, for the loss of goodwill, prospective profits or anticipated income, or for any expenditures, investments, leases or commitments made by either Merchant or Toppings.</li>
            <li><b>Modifications.</b> Toppings reserves the right, at its sole discretion, to change, suspend, or discontinue the Platform (including without limitation, the availability of any feature or content) at any time. Toppings may, at its sole discretion, remove Merchant Products or Stores from the Toppings Platform if Toppings determines that such Merchant Product or Merchant Store could subject Toppings to undue regulatory risk, health and safety risk, or other liability. Toppings also may revise these Terms from time to time. The changes will not be retroactive, and the most current version of the terms will be at FIGURE DIS OUT We will notify Merchants of material revisions via a service notification or an email to the email address associated with your account. By continuing to access or use the Services after those revisions become effective, you agree to be bound by the revised Terms.</li>
            <li><b>Representations and Warranties; Additional Responsibilities; Warranty Disclaimer.</b>
              <ol>
                <li>Each party represents and warrants that it has the full right, power, and authority to enter into and perform its obligations under this Agreement without breaching any obligation to any third party.</li>
                <li>Each party represents and warrants that it will comply with all applicable laws and regulations in its performance of this Agreement, including without limitation (i) all applicable data protection and privacy laws, and (ii) all applicable laws related to third party intellectual property and other proprietary rights.</li>
                <li>Merchant further represents, warrants and agrees that (i) it will comply with all applicable laws, rules, standards and regulations relating to licenses, health (including Proposition 65 in California), food packaging and accessory items (including but not limited to foodware, plasticware, and other disposable restaurant supplies), and food safety and sanitation, (ii) it has informed Toppings of any required consumer-facing warnings, charges, opt-in requirements, and instructions associated with Merchant Product(s) and it will inform Toppings of any such warnings, charges, opt-ins, and instructions that become required in the future, (iii) it will disclose common allergens in any Merchant’s menu items listed on the Toppings Platform, (iv) it will only list menu items or products for sale, product descriptions, and prices on the Toppings Platform,  (v) it will not include any age-restricted products (including but not limited to alcohol and tobacco) in Merchant’s menus on the Toppings Platform or request delivery of any age-restricted products through the Toppings Platform without first entering into a separate agreement with Toppings memorializing the promotion, sale and delivery of such products in compliance with the laws of the applicable state in which such products will be sold, (vi) it will not disclose any information related to a Topper or a Customer to a third party (except as required to comply with law or pursuant to a court order), (vii) it will comply with the guidelines Toppings publishes that govern any content Merchant posts on the Toppings Platform or Merchant Portal, and  (viii) it will comply with its obligations under Section 4(b)(iii) and 4(b)(iv) of this Agreement.</li>
                <li>EXCEPT AS EXPRESSLY SET FORTH HEREIN, TO THE EXTENT PERMITTED BY APPLICABLE LAW, TOPPINGS HEREBY EXPRESSLY DISCLAIMS ALL WARRANTIES, EXPRESS, IMPLIED OR STATUTORY, REGARDING THE TOPPINGS PLATFORM, THE DELIVERY API, EQUIPMENT OR SERVICES, INCLUDING BUT NOT LIMITED TO ANY IMPLIED WARRANTIES OF MERCHANTABILITY, TITLE, SATISFACTORY QUALITY OR RESULTS, OR FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. Merchant acknowledges that the operation of the Platform may from time to time encounter technical or other problems and may not necessarily continue uninterrupted or without technical or other errors and Toppings shall not be responsible to Merchant or others for any such interruptions, errors, or problems or an outright discontinuance of the Platform nor for any guarantee of results with respect to the Toppings services or Platform. Both Parties acknowledge that neither party has any expectation or has received any assurances for future business or that any investment by a party will be recovered or recouped or that such party will obtain any anticipated amount of profits by virtue of this Agreement.</li>
              </ol>
            </li>
            <li><b>Indemnification.</b> Each party (the “Indemnifying Party”) will defend, indemnify, and hold harmless the other party, its subsidiaries and affiliates, and their respective officers, directors, shareholders, employees, and agents (the “Indemnified Party”) from and against any and all claims, damages, losses and expenses (including reasonable attorney’s fees) (collectively “Losses”) with respect to any third-party claims arising out of or related to: (i) any bodily injury (including death) or damage to tangible or real property to the extent caused by the Indemnifying Party’s personnel and, in the case of Toppings, Toppers (or, in the case of Merchant as the Indemnifying Party, caused by the Merchant Products); (ii) any claims that the Indemnifying Party breached its representations, warranties or covenants set forth in Section 11 and Section 12, and Section 15 of this Agreement; (iii) the violation of the intellectual property of the third party by the Indemnifying Party’s logos, trademarks, trade names, menus, documentation, or other intellectual property (collectively, “Materials”); or (iv) in the case of Merchant as the Indemnifying Party, Merchant’s failure to distribute tips as required by applicable law. In addition, Merchant will defend, indemnify and hold harmless Toppings from any and all Losses related to any violation or alleged violation of any applicable retail food or other health and safety code, rule, or regulation related to Merchant Product(s), except to the extent such Losses were caused directly by the gross negligence or willful misconduct of Toppings. In each case the Indemnified Party shall provide the Indemnifying Party with (a) prompt notice of any claims such that the Indemnifying Party is not prejudiced by any delay of such notification, (b) the option to assume sole control over defense and settlement of any claim, and (c) reasonable assistance in connection with such defense and settlement (at the Indemnifying Party’s expense). The Indemnified Party may participate in the defense or settlement of such a claim with counsel of its own choice and at its own expense; however, the Indemnifying Party shall not enter into any settlement agreement that imposes any obligation on the Indemnified Party without the Indemnified Party’s express prior written consent. Toppings assumes no liability, and shall have no liability, for any infringement claim pursuant to section 16(iii) above based on Merchant’s access to and/or use of the Toppings Platform following notice of such an infringement claim; any unauthorized modification of the Toppings Platform by Merchant; or Merchant’s combination of the Toppings Platform with third party programs, services, data, hardware, or other materials which otherwise would not result in such infringement claim.</li>
            <li><b>Limitation of Liability. </b>EXCEPT WITH RESPECT TO DAMAGES ARISING FROM VIOLATIONS OF LAW OR WILFUL MISCONDUCT, UNPAID AMOUNTS OWED TO TOPPINGS BY MERCHANT IN EXCESS OF THE BELOW LIMIT, AND AMOUNTS PAYABLE TO THIRD PARTIES UNDER SECTION 16 (INDEMNIFICATION), TO THE EXTENT PERMITTED BY APPLICABLE LAW, (I) NEITHER PARTY WILL BE LIABLE TO THE OTHER UNDER THIS AGREEMENT, FOR INDIRECT, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES, OR FOR LOST PROFITS, LOST REVENUES, HARM TO GOODWILL, OR THE COSTS FOR PROCURING REPLACEMENT SERVICES, WHETHER BASED ON TORT, CONTRACT OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT SUCH PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, AND (II) EACH PARTY’S MAXIMUM AGGREGATE LIABILITIES RELATED TO OR IN CONNECTION WITH THIS AGREEMENT SHALL NOT EXCEED THE TOTAL AMOUNT PAID OR PAYABLE BY ONE PARTY TO THE OTHER PARTY IN THE TWELVE (12) MONTH PERIOD IMMEDIATELY PRECEDING THE INCIDENT GIVING RISE TO THE LIABILITY. THE FOREGOING DISCLAIMER SHALL NOT APPLY TO THE EXTENT PROHIBITED BY LAW.</li>
            <li><b>Insurance. </b>During the term of the Agreement and for one year after, each party will maintain adequate insurance in amounts not less than as required by law or that is common practice in such party’s business. Upon request, each party will provide the other with current evidence of coverage. Such insurance shall not be cancelled or materially reduced without thirty (30) days prior written notice. In no event shall the limits of any insurance policy be considered as limiting the liability of a party under this Agreement.</li>
            <li><b>Dispute Resolution.</b> PLEASE READ THE FOLLOWING SECTION CAREFULLY. IT REQUIRES YOU TO ARBITRATE DISPUTES WITH TOPPINGS AND LIMITS THE MANNER IN WHICH YOU CAN SEEK RELIEF. THIS SECTION 19 OF THIS AGREEMENT SHALL BE REFERRED TO AS THE “ARBITRATION AGREEMENT”.
              <ol>
                <li><b>Scope of Arbitration Agreement.</b> Any dispute, controversy or claim arising out of, relating to or in connection with this contract, including the breach, termination or validity thereof, shall be finally resolved by binding arbitration, rather than in court, except that (1) you may assert claims in small claims court if your claims qualify, so long as the matter remains in such court and advances only on an individual (non-class, non-representative) basis; and (2) you or Toppings may seek injunctive relief in court for infringement or other misuse of intellectual property rights (such as trademarks, trade dress, domain names, trade secrets, copyrights, and patents). Toppings and Merchant agree that, because both are business entities that mutually benefit from streamlined and confidential resolution, this Arbitration Agreement shall apply to all disputes arising from or relating to the subject matter of this Agreement or the relationship between the parties and their personnel. In that regard, this Arbitration Agreement shall be binding upon and enforceable by not only the parties, but also their affiliates, and their owners, officers, directors, managers and employees. This Arbitration Agreement shall apply, without limitation, to all claims that arose or were asserted before the Effective Date of this Agreement. CASES HAVE BEEN FILED AGAINST TOPPINGS—AND OTHERS MAY BE FILED IN THE FUTURE—THAT ATTEMPT TO ASSERT CLASS ACTION CLAIMS, AND BY ACCEPTING THIS ARBITRATION AGREEMENT YOU ELECT NOT TO PARTICIPATE IN SUCH CASES. IF YOU AGREE TO ARBITRATION WITH TOPPINGS, YOU ARE AGREEING IN ADVANCE THAT YOU WILL NOT PARTICIPATE IN OR SEEK TO RECOVER MONETARY OR OTHER RELIEF IN ANY SUCH CLASS, COLLECTIVE, AND/OR REPRESENTATIVE LAWSUIT. INSTEAD, BY AGREEING TO ARBITRATION, YOU MAY BRING YOUR CLAIMS AGAINST TOPPINGS IN AN INDIVIDUAL ARBITRATION PROCEEDING. IF SUCCESSFUL ON SUCH CLAIMS, YOU COULD BE AWARDED MONEY OR OTHER RELIEF BY AN ARBITRATOR.</li>
                <li><b>Informal Resolution. You and Toppings agree that good-faith informal efforts to resolve disputes often can result in a prompt, low-cost and mutually beneficial outcome. You and Toppings therefore agree that, before either you or Toppings demands arbitration against the other, we will personally meet and confer, via telephone or videoconference, in a good-faith effort to resolve informally any claim covered by this mutual Arbitration Agreement. If you are represented by counsel, your counsel may participate in the conference, but you shall also fully participate in the conference. The party initiating the claim must give notice to the other party in writing of its, his, or her intent to initiate an informal dispute resolution conference, which shall occur within 60 days after the other party receives such notice, unless an extension is mutually agreed upon by the parties. To notify Toppings that you intend to initiate an informal dispute resolution conference, email Merchant.Informal.Resolution@Toppings.com, providing your name, telephone number associated with your Toppings account (if any), the email address associated with your Toppings account, and a description of your claim. In the interval between the party receiving such notice and the informal dispute resolution conference, the parties shall be free to attempt to resolve the initiating party’s claims. Engaging in an informal dispute resolution conference is a requirement that must be fulfilled before commencing arbitration.  The statute of limitations and any filing fee deadlines shall be tolled while the parties engage in the informal dispute resolution process required by this paragraph.</b></li>
                <li><b>Arbitration Rules and Forum.</b> This Arbitration Agreement is governed by the Federal Arbitration Act in all respects. If for whatever reason the rules and procedures of the Federal Arbitration Act cannot apply, the state law governing arbitration agreements in the state in which you reside shall apply. Before a party may begin an arbitration proceeding, that party must send notice of an intent to initiate arbitration and certifying completion of the informal dispute resolution conference pursuant to paragraph 19(2). If this notice is being sent to Toppings, it must be sent by email to the counsel who represented Toppings in the informal dispute resolution process, or if there was no such counsel then by mail to General Counsel, at 5190 Ivy Nole Cumming, GA 30040. The arbitration will be conducted by JAMS under its rules and pursuant to the terms of this Agreement, but in the event of a conflict between the two, the provisions of this Arbitration Agreement shall supersede any and all conflicting arbitration administrator’s rules or procedures. Arbitration demands filed with JAMS must include (1) the name, telephone number, mailing address, and e-mail address of the party seeking arbitration; (2) a statement of the legal claims being asserted and the factual bases of those claims; (3) a description of the remedy sought and an accurate, good-faith calculation of the amount in controversy, enumerated in United States Dollars (any request for injunctive relief or attorneys’ fees shall not count toward the calculation of the amount in controversy unless such injunctive relief seeks the payment of money); and (4) the signature of the party seeking arbitration. Disputes involving claims and counterclaims under $250,000, not inclusive of attorneys’ fees and interest, shall be subject to JAMS’s most current version of the Streamlined Arbitration Rules and procedures available at http://www.jamsadr.com/rules-streamlined-arbitration/; all other claims shall be subject to JAMS’s most current version of the Comprehensive Arbitration Rules and Procedures, available at http://www.jamsadr.com/rules-comprehensive-arbitration/. JAMS’s rules are also available at www.jamsadr.com (under the Rules/Clauses tab) or by calling JAMS at 800-352-5267. Payment of all filing, administration, and arbitration fees will be governed by JAMS’s rules. If JAMS is not available to arbitrate, the parties will select an alternative arbitral forum. You may choose to have the arbitration conducted by telephone, video conference, or in person in the country where you live or at another mutually agreed location.</li>
                <li><b>Arbitrator Powers.</b> The arbitrator, and not any federal, state, or local court or agency, shall have exclusive authority to resolve any dispute relating to the interpretation, applicability, enforceability or formation of this Arbitration Agreement including, but not limited to any claim that all or any part of this Arbitration Agreement is void or voidable. All disputes regarding the payment of arbitrator or arbitration-organization fees including the timing of such payments and remedies for nonpayment, shall be determined exclusively by an arbitrator, and not by any court. The arbitration will decide the rights and liabilities, if any, of you and Toppings. The arbitration proceeding will not be consolidated with any other matters or joined with any other proceedings or parties. The arbitrator will have the authority to grant motions dispositive of all or part of any claim or dispute. The arbitrator will have the authority to award monetary damages and to grant any non-monetary remedy or relief available to an individual under applicable law, the arbitral forum’s rules, and this Agreement (including this Arbitration Agreement). The arbitrator will issue a written statement of decision describing the essential findings and conclusions on which any award (or decision not to render an award) is based, including the calculation of any damages awarded. The arbitrator shall follow the applicable law. The arbitrator has the same authority to award relief on an individual basis that a judge in a court of law would have. The arbitrator’s decision is final and binding on you and Toppings.</li>
                <li><b>Waiver of Jury Trial.</b>YOU AND TOPPINGS WAIVE ANY CONSTITUTIONAL AND STATUTORY RIGHTS TO SUE IN COURT AND RECEIVE A JUDGE OR JURY TRIAL. You and Toppings are instead electing to have claims and disputes resolved by arbitration, except as specified in Section 19(1) above. There is no judge or jury in arbitration, and court review of an arbitration award is limited.</li>
                <li><b>Waiver of Class or Consolidated Actions; Severability.</b> YOU AND TOPPINGS AGREE TO WAIVE ANY RIGHT TO RESOLVE CLAIMS WITHIN THE SCOPE OF THIS ARBITRATION AGREEMENT ON A CLASS, COLLECTIVE, OR REPRESENTATIVE BASIS. ALL CLAIMS AND DISPUTES WITHIN THE SCOPE OF THIS ARBITRATION AGREEMENT MUST BE ARBITRATED ON AN INDIVIDUAL BASIS AND NOT ON A CLASS BASIS. CLAIMS OF MORE THAN ONE MERCHANT CANNOT BE ARBITRATED OR LITIGATED JOINTLY OR CONSOLIDATED WITH THOSE OF ANY OTHER CUSTOMER OR USER. If, however, this waiver of class or consolidated actions is deemed invalid or unenforceable with respect to a particular claim or dispute, neither you nor Toppings is entitled to arbitration of such claim or dispute. Instead, all such claims and disputes will then be resolved in a court as set forth in Section 20, and all other provisions of this Section 19 (Dispute Resolution) shall remain in force. If any provision of this Section 19 is adjudged to be void or otherwise unenforceable, in whole or in part, the void or unenforceable provision shall be severed and such adjudication shall not affect the validity of the remainder of this Section 19. Nothing in this provision shall prevent you or Toppings from participating in a class-wide settlement of claims.</li>
                <li><b>Opt Out.</b> Toppings’s updates to these Terms of Service do not provide a new opportunity to opt out of the Arbitration Agreement if you had previously agreed to a version of Toppings’s Terms of Service and did not validly opt out of arbitration. Toppings will continue to honor the valid opt outs of merchants who validly opted out of the Arbitration Agreement in a prior version of the Terms of Service. If you create a Toppings account for the first time on or after December 9, 2020, you may opt out of this Arbitration Agreement. If you do so, neither you nor Toppings can force the other to arbitrate as a result of this Agreement. To opt out, you must notify Toppings in writing of your intention to opt out by sending a letter, by First Class Mail, to Toppings, Inc., 5190 Ivy Nole Cumming GA 30040. Any attempt to opt out by email will be ineffective. To be effective, your opt-out notice must be postmarked no later than 30 days after your first order on the Platform. Your notice must include your name and address, your Toppings username (if any), the email address you used to set up your Toppings account (if you have one), and a CLEAR statement that you want to opt out of this Arbitration Agreement. The letter may opt out, at most, only one merchant, and letters that purport to opt out multiple merchants will not be effective as to any. No merchant (or his or her agent or representative) may effectuate an opt out on behalf of other persons. If you opt out of this Arbitration Agreement, all other parts of this Agreement will continue to apply to you. Opting out of this Arbitration Agreement has no effect on any other arbitration agreements that you may have entered into with us or may enter into in the future with us.</li>
                <li><b>Survival. This Arbitration Agreement will survive any termination of your relationship with Toppings.</b></li>
                <li><b>Modification. Notwithstanding any provision in the Agreement to the contrary, we agree that if Toppings makes any future material change to this Arbitration Agreement, it will not apply to any individual claim(s) that you had already provided notice of to the Company.</b></li>
              </ol>
            </li>
            <li><b>Litigation Class Action Waiver. To the extent allowed by applicable law, separate and apart from the Mutual Arbitration Provision found in Section 19, Merchant agrees that any proceeding to litigate in court any dispute arising out of or relating to this Agreement, whether because Merchant opted out of the Arbitration Provision or any other reason, will be conducted solely on an individual basis, and Merchant agrees not to seek to have any controversy, claim or dispute heard as a class action, a representative action, a collective action, a private attorney-general action, or in any proceeding in which Merchant acts or proposes to act in a representative capacity (“Litigation Class Action Waiver”). Merchant further agrees that no proceeding will be joined, consolidated, or combined with another proceeding, without the prior written consent of all parties to any such proceeding. If a court of competent jurisdiction determines that all or part of this Litigation Class Action Waiver is unenforceable, unconscionable, void or voidable, the remainder of this Agreement shall remain in full force and effect.</b></li>
            <li><b>Franchisees.</b>Franchisees operating a branded restaurant or store concept licensed by Merchant may participate in the Program pursuant to the terms and conditions of this Agreement provided that the individual franchisee: (1) is in compliance with its franchise agreement; and (2) enters into an agreement in substantially the same form as the Supplemental Agreement provided by Toppings to the Franchisee. Unless the parties mutually agree otherwise in writing, all Merchant owned branded restaurant(s) and store concept(s) shall be included and subject to the terms hereunder.</li>
            <li><b>Communications from Toppings.</b> Merchant agrees to accept and receive communications from Toppings or Toppers, including via email, text message, calls, and push notifications to the cellular telephone number Merchant provides to Toppings. Merchant acknowledges that Merchant may receive communications generated by automatic telephone dialing systems and/or which will deliver prerecorded messages sent by or on behalf of Toppings, its affiliated companies and/or Toppers. Merchant may opt out of such communications in Merchant’s Account Settings or by replying “STOP” from the mobile device receiving such messages.</li>
            <li><b>Attorneys’ Fees.</b> In any legal action to enforce the terms of this Agreement, the prevailing party in such action shall be entitled to recover its reasonable attorneys’ fees and costs from the other party.</li>
            <li><b>General Provisions.</b> As set forth on the Sign-Up Sheet between Merchant and Toppings, the Sign-Up Sheet and these Terms constitute an integrated Agreement between the parties, which supersedes all prior agreements and communications of the parties, oral or written, with respect to the subject matter hereof. The rights and obligations set forth in these Terms, which by their nature should, or by their express terms do, survive or extend beyond the termination or expiration of these Terms shall so survive and extend. This Agreement is governed by and interpreted in accordance with the laws of the State of Delaware without regard to the conflicts of laws principles thereof. Merchant agrees that, except as set forth above in Section 19 (“Dispute Resolution”), the parties hereby consent to exclusive jurisdiction in the courts of the Merchant’s location. Merchant may not assign this Agreement in whole or in part without Toppings’s prior written consent. Toppings may freely assign this Agreement. This Agreement is binding upon, and inures to the benefit of, the employees, representatives, agents, affiliates, franchisors, franchisees, and permitted successors and assigns of each party, but shall not confer any rights or remedies upon any third party. All notices, requests, consents and other communications under the Parties' agreements must be in writing, and delivered by overnight courier to the addresses set forth on the Sign-Up Sheet (or any updated address properly noticed hereunder). Toppings’s address is 5190 Ivy Nole, Cumming, GA 30040. If any provision of this Agreement is held to be invalid, illegal or unenforceable for any reason, such invalidity, illegality or unenforceability will not affect any other provisions of this Agreement, and this Agreement will be construed as if such invalid, illegal or unenforceable provision had never been contained here.</li>
          </ol>
        </div>

        <button>Export as PDF</button>
      </div>
    </article>
  );
}

export default PortalTermsService;
